### ISSUE TITLE
[conda] Unable to make a conda build

### ISSUE THREAD

**Issue by fg-mindee** [mindee/doctr#113]
Unfortunately, one of the project dependencies does not have any conda release or any way to make one. I opened an issue on their repo https://github.com/pymupdf/PyMuPDF/issues/938 to track this, but so far I haven't found any way to release the project on anaconda with this dependency.

**Comment by charlesmindee** [comment]
Is it mandatory to support conda? If so, maybe we can switch to another pdf-reader lib.

**Comment by fg-mindee** [comment]
Not mandatory but this is a very common installation mean for python package. We might investigate other options to replace the dependency but we'll have to check for performance drop first

**Comment by kchawla-pi** [comment]
Why not simply do a
```shell
conda run pip install <missing in conda package>
```
Especially since there's is only one package

**Comment by fg-mindee** [comment]
Hi @kchawla-pi,

So actually since then, there is also `weasyprint` that is missing a conda build. But it happens that I was thinking about getting back to the bottom of this yesterday. Worst case scenario, we'll make some features optional (such as HTML compatibility through weasyprint) so that the core build is available in conda.

Also please note that for now, the only important dependencies that would benefit from a conda support (performance-wise) are PyTorch & TensorFlow :+1: 

Anyway, we'll provide some updates on this very topic soon!

**Comment by charlesmindee** [comment]
So now with #829 we are just missing `weasyprint`, right @fg-mindee ?

**Comment by fg-mindee** [comment]
> So now with #829 we are just missing `weasyprint`, right @fg-mindee ?

Nope, pypdfium2 also lacks support of a conda installation. But that could be fixed, I'll ping them about this!
However, having `doctr.io.pdf` and `doctr.io.html` as extras, would do the trick :+1: 

And I think we should seriously consider that: especially for HTML, it's more about people in need of training data, so I would argue that most users don't benefit from weasyprint (which is a problem for MAC users also #815)

For PDFs, it's more important, so if we can get a conda build, our best course of action would probably be to move html/weasyprint to an extra! What do you think?

**Comment by fg-mindee** [comment]
I just checked and weasyprint does have a conda build now :raised_hands: 
https://anaconda.org/conda-forge/weasyprint

(But I still think we should move it to extra builds)

**Comment by felixdittrich92** [comment]
@frgfm

**Comment by frgfm** [comment]
@mara004 what do you mean by "any reason you can't use pip?"

pip installation is already available 👍 
but conda builds are more specific to a given environment, so it's good if we can offer that mean of installation as well. For the conda recipe, I don't know about options to use pip (I don't have experience with conda recipe building the C or C++ extensions of a python library though)

**Comment by mara004** [comment]
> what do you mean by "any reason you can't use pip?"

I'm not familiar with the conda environment, so perhaps that was a silly question to ask.
I basically meant: For what reason do we need an extra package on conda if the PyPI release can be used instead?
As @kchawla-pi wrote:
> Why not simply do a
> ```
> conda run pip install <missing in conda package>
> ```

> but conda builds are more specific to a given environment

I'd be curious to know in what way exactly conda builds are more specific?

**Comment by kchawla-pi** [comment]
Well, pip does not do sophisticated dependency resolution, unlike Conda. It's the same reason pipenv and poetry are used for package installations, but unlike Conda, they use PyPI's index. Each of these has their own algorithm for dependency resolution, with Pipenv being rather slow.

Conda is the defacto tool for data scientists in the Python ecosystem. Seamlessly using Mindee using Conda will solve a big paper cut.

**Comment by mara004** [comment]
Okay, thanks for pointing this out!
From a developer's perspective, conda still seems kind of a reinvented wheel and duplicated packaging work to me, but if there are people who like it and use it I'm definitely open to add support if someone can help me with the implementation.

**Comment by frgfm** [comment]
I can definitely second @kchawla-pi on that: I always try to find a conda installation before using pip, because it's much more careful about your existing env compatibility 👍

**Comment by mara004** [comment]
I tried to craft a package with `conda-build` recently but unfortunately it didn't go very well at all. I managed to build a package for my host platform (Linux x86_64) but it took unendurably long for conda-build to set up the environment and assemble the package. The place where the artifacts are put isn't straightforward either. Unless there are ways to radically speed up the process of running conda-build, I don't think there's a realistic possibility we can do this.

**Comment by frgfm** [comment]
In my experience conda build is always a long operation. Base conda is known to have a slow dep resolution procedure, so I personally use mamba (https://github.com/mamba-org/mamba) which is blazing fast for dep installation (multi-thread, rewritten in C++). I have to check if that extends to package building as well

**Comment by mara004** [comment]
I think the main problem is that, when running conda-build, it creates an isolated environment where all dependencies are installed. Now, if we want to craft more than one package, it would be essential that the environment can be reused so that dependencies don't need to be installed each time. Is there any option to do this?

**Comment by felixdittrich92** [comment]
@frgfm do you now an answer ? :sweat_smile:

**Comment by mara004** [comment]
Even if we can get around the duration problem, I'll still need information about conda platform tags. We need an equivalent for each of the tags shown on https://pypi.org/project/pypdfium2/#files (section "Built Distributions").

**Comment by mara004** [comment]
For reference, these two pages sound interesting:
https://docs.conda.io/projects/conda-build/en/latest/user-guide/recipes/build-without-recipe.html
https://docs.conda.io/projects/conda-build/en/latest/user-guide/wheel-files.html

**Comment by mara004** [comment]
Found the platform identifiers. `conda convert` actually lists them: `osx-64,osx-arm64,linux-32,linux-64,linux-ppc64,linux-ppc64le,linux-s390x,linux-armv6l,linux-armv7l,linux-aarch64,win-32,win-64,all`

**Comment by mara004** [comment]
Sorry for spamming this thread! Anyway, I'm at it with the conda build. I don't want to promise anything too early, but I believe to have finally found a reasonable approach. I've got the conda recipe and commands together locally and am about to integrate it into the setup infrastructure.

**Comment by mara004** [comment]
Got relatively far but am stuck with the problem that `conda convert` doesn't work for `noarch` packages, see https://github.com/conda/conda-build/issues/2611

**Comment by mara004** [comment]
Tried an alternative approach using the host platform as intermediary, but now I have the problem that packages are built for a specific Python version, which is not what we want. If we find some way to get around this, it would be done (though it's not exactly nice).

**Comment by frgfm** [comment]
I'm not very knowledgeable about `conda convert` command unfortunately!
Regarding the duration, I've had similar issues and there appears to be no workarounds (I'm waiting for mamba build, since mamba is a rewrite of conda but much faster & parallel processing)

**Comment by mara004** [comment]
What I think could be done relatively easily would be to add the required files for users to create/install a conda package locally.
For this, one could treat pypdfium2 just like any other `noarch: python` package, but then we obviously don't get uploadable artefacts.
With a rather dreadful workaround, I did manage to build architecture-specific conda packages locally, but the problem is that conda always ties them to a single python version, although this is not necessary for ABI-level bindings. But I'm definitely not willing to go the path of python-specific builds, that would be horribly inelegant. IMO, this is only feasible if conda is changed to allow python-independent architecture-specific builds somehow.

**Comment by kchawla-pi** [comment]
Assuming your work is open source, where can I see your recipe and efforts,
to build off of?

**Comment by felixdittrich92** [comment]
Hi @kchawla-pi 👋 ,
Yes the project is open source (Apache 2.0 License). What do you mean with recipe / efforts related to conda build ? Could you explain a bit more in detail what you need ? 😅

**Comment by mara004** [comment]
@felixdittrich92 I think @kchawla-pi meant me, right?
pypdfium2 is open source indeed, but I deleted the conda branch out of sheer frustration. Some attempts I never even pushed. Anyway, the state wasn't good at all and you're probably better off starting from scratch if you want to make an attempt yourself.

**Comment by harindercnvrg** [comment]
@felixdittrich92 @mara004 is there any update on creating conda builds?

**Comment by mara004** [comment]
Has anything changed in conda yet?

**Comment by harindercnvrg** [comment]
@mara004 I am not sure. 
I saw these benchmarks and I assumed it is now possible to build doctr using conda.
https://github.com/mindee/doctr/discussions/1094

The speedup is pretty impressive.

**Comment by mara004** [comment]
I think, these benchmarks are just about the tensorflow/pytorch builds used.
And apparently, anaconda manages to procure more optimized builds by default.

However, in the end it's really just the binaries that matter, i. e. if you compiled the project in question with optimal config for the target platform, any tool could be used to install the result. The only thing conda does is smartly find/make better binaries for you.

**Comment by harindercnvrg** [comment]
Hey, thanks for the suggestion. I tried the conda binaries for torch only but it did not lead to any speed up.

**Comment by mara004** [comment]
Since it looks like the packages generated from pypdfium2-feedstock will not be made public (cf. https://github.com/AnacondaRecipes/pypdfium2-feedstock/issues/1#issuecomment-1681043844), I will make a second attempt at building official conda packages for pypdfium2 in a [conda branch](https://github.com/pypdfium2-team/pypdfium2/compare/main...conda), trying to accept or work around the python version problem (it remains to be decided how).

pypdfium2-feedstock currently requires manual interaction and native hosts.[^1] I want to design this differently so we can build automatically in a workflow and without native hosts.

[^1]: This is only possible due to anaconda's extended CI capabilities, and might still end up not supporting some platforms we technically have binaries for.

**Comment by mara004** [comment]
Ok, so I think I have the local packaging part ready. It's really inelegant, but all I could do given conda's limitations.

Now the remaining parts we need are
* CI integration 
  - build in parallel for the multiple python versions (I'd suggest 3.8 through 3.11)
  - upload to anaconda (help wanted)
* People who can test the built packages

Here's an archive of builds for python 3.11 which I generated locally: [pypdfium2_conda_py311.zip](https://github.com/mindee/doctr/files/12388238/pypdfium2_conda_py311.zip)

(PS: @kchawla-pi, now you can take a look at the code if you like ;) )

**Comment by mara004** [comment]
Oh, and I just discovered conda's `--variants` feature - we can pass `{python: [3.8, 3.9, 3.10, 3.11]}` to build for multiple python versions. That doesn't really fix the problem (we still end up with separate packages although not logically necessary), but it makes it easier to accommodate, and hints that there may be at least some upstream recognition of the problem.

**Comment by felixT2K** [comment]
Hi @mara004 
Thanks for the updates :+1: 

About uploading this seems not to be so complicated: https://levelup.gitconnected.com/publishing-your-python-package-on-conda-and-conda-forge-309a405740cf   (manual upload)

and with CI:
https://github.com/frgfm/Holocron/blob/f78c6c58c0007e3d892fcaa1f1ff786cdbb5195f/.github/workflows/release.yml#L58
https://github.com/frgfm/Holocron/tree/main/.conda

Maybe @frgfm can help a bit more :)

**Comment by mara004** [comment]
Throwback, @boldorider4 just gave me an eye opener that pdfium should be packaged separately in conda so pypdfium2 can just depend on it and cleanly be noarch. I'm still thinking about this but believe it may finally be *the* clean solution I was looking for.
Ideally pdfium-binaries would just upload to conda directly, then the only remaining piece is to instruct the library loader with the right path.

This should really have come to my mind earlier. Especially I should have realized after a recent discussion with @kolanich about pdfbox, just failed to connect it.

**Comment by felixT2K** [comment]
@mara004 fyi there is also a draft for `conda-forge` channel: 

https://github.com/conda-forge/staged-recipes/pull/23726

**Comment by mara004** [comment]
> @mara004 fyi there is also a draft for conda-forge channel:
> https://github.com/conda-forge/staged-recipes/pull/23726

Thanks for the pointer,  see my comment https://github.com/conda-forge/staged-recipes/pull/23726#issuecomment-1688169659.

**Comment by felixT2K** [comment]
@mara004 I wanted to ask if there are any updates on your site ? :)

**Comment by mara004** [comment]
> @mara004 I wanted to ask if there are any updates on your site ? :)

I've got it on my mind and have been working on some integration prerequisites to get this done nicely - packaging with an external library differs quite a bit from bundling. I can elaborate on the individual tasks if necessary.
The thing is, my personal situation is a bit difficult, but provided it doesn't get worse I should hopefully be able to finish this well before year's end.

**Comment by felixT2K** [comment]
> > @mara004 I wanted to ask if there are any updates on your site ? :)
> 
> I've got it on my mind and have been working on some integration prerequisites to get this done nicely - packaging with an external library differs quite a bit from bundling. I can elaborate on the individual tasks if necessary. The thing is, my personal situation is rather difficult, but provided it doesn't get worse I should hopefully be able to finish this well before year's end.

Oh yeah, no stress, I just wanted to ask so I can plan for it. :)

**Comment by mara004** [comment]
Work in progress: https://github.com/pypdfium2-team/pypdfium2/pull/268/files
I believe the packaging is nearly done, we just need some cleanup, testing and the CI integration now.

**Comment by mara004** [comment]
However, we might have a bit of a problem with the custom channels.
According to https://github.com/conda/conda-build/issues/532#issuecomment-410244068, it looks like conda-build does not properly support them in recipes?

In that case, users would have to add the channels explicitly before installation, which is probably doable, but not nice.
Especially we need to be careful with pdfium-binaries, because there's an improper package in anaconda-main (the official channel is bblanchon), which adds to the confusion.

**Comment by mara004** [comment]
Just merged the conda packaging code: https://github.com/pypdfium2-team/pypdfium2/commit/ee5a2ff3106052d5874107bcb11c95a8c5dfdbc4.
The packages build locally, but I haven't done the CI integration yet.

**Comment by mara004** [comment]
And the CI/docs also merged now: https://github.com/pypdfium2-team/pypdfium2/pull/269

**Comment by mara004** [comment]
https://anaconda.org/pypdfium2-team/pypdfium2_helpers
https://github.com/pypdfium2-team/pypdfium2#installation

**Comment by felixT2K** [comment]
Thanks a lot @mara004 👍🏼

**Comment by frgfm** [comment]
Thanks @mara004, it looks like we're gonna be able to get docTR on anaconda now!
Here are all docTR deps as of now & their support of conda:

Default channels
- [x] numpy
- [x] scipy
- [x] h5p
- [x] matplotlib
- [x] Pillow

Conda forge
- [x] opencv (https://anaconda.org/conda-forge/opencv)
- [x] pyclipper (https://anaconda.org/conda-forge/pyclipper)
- [x] shapely (https://anaconda.org/conda-forge/shapely)
- [x] langdetect (https://anaconda.org/conda-forge/langdetect)
- [x] rapidfuzz (https://anaconda.org/conda-forge/rapidfuzz)
- [x] weasyprint (https://anaconda.org/conda-forge/weasyprint)
- [x] defusedxml (https://anaconda.org/conda-forge/defusedxml)
- [x] mplcursors (https://anaconda.org/conda-forge/mplcursors)
- [x] unidecode (https://anaconda.org/conda-forge/unidecode)
- [x] tqdm (https://anaconda.org/conda-forge/tqdm)
- [x] huggingface hub (https://anaconda.org/conda-forge/huggingface_hub)

Custom channels
- [x] pypdfium (https://github.com/pypdfium2-team/pypdfium2#install-conda)

Just gotta put together a conda recipe. Building it might be long for the dependency resolution + check considering the amount of deps, but it should work :+1: (we might have some surprises on some OS though)

**Comment by mara004** [comment]
FWIW, someone has put pypdfium2 in conda-forge now, but badly.
As of this writing, they only support osx-64 and macos-64, and as they're bundling the binaries, they have to build python version specific packages, unnecessarily.
Again, it's tied to native hosts, and as such will always lack support for any architectures not provided by the feedstock infrastructure.

https://anaconda.org/conda-forge/pypdfium2
https://anaconda.org/conda-forge/pypdfium2/files
https://anaconda.org/conda-forge/ctypesgen-pypdfium2-team

**Comment by felixdittrich92** [comment]
Thanks for the update 👍

**Comment by mara004** [comment]
https://github.com/mindee/doctr/discussions/2127 has some updates on the topic (sorry it got so long 😅).

In particular, the problem that came up here – conda not supporting platform-specific but interpreter independent python packages back then – seems to have been addressed upstream with [CEP 20](https://github.com/conda/ceps/blob/ff39eb01d1664d041f8733659a344620be1d6c2d/cep-0020.md).

The third-party [conda-forge port](https://github.com/conda-forge/pypdfium2-feedstock) still seems to be in a miserable state.
However I was intrigued to see that the [anaconda/main port](https://github.com/AnacondaRecipes/pypdfium2-feedstock) appears to have matured somewhat (it's now building pdfium from source) but I haven't thoroughly checked it yet. Building against conda system libraries sounds like a risky business though (do they have any mechanism to ensure compatibility / ABI safety ???). Anyway, I'm not able to support that upstream – if you run into issues you'd have to report them to the third-party recipe maintainers.

**Comment by felixdittrich92** [comment]
> [#2127](https://github.com/mindee/doctr/discussions/2127) has some updates on the topic.
> 
> In particular, the problem that came up here – conda not supporting platform-specific but interpreter independent python packages back then – seems to have been addressed upstream with [CEP 20](https://github.com/conda/ceps/blob/ff39eb01d1664d041f8733659a344620be1d6c2d/cep-0020.md).
> 
> The third-party [conda-forge port](https://github.com/conda-forge/pypdfium2-feedstock) still seems to be in a miserable state. I was intrigued to see that the [anaconda/main port](https://github.com/AnacondaRecipes/pypdfium2-feedstock) appears to have matured somewhat (it's now building pdfium from source) but I haven't thoroughly checked it yet. Building against conda system libraries sounds like a risky business though (do they have any mechanism to ensure compatibility / ABI safety ???). Anyway, I'm not able to support that upstream – if you run into issues you'd have to report them to the third-party recipe maintainers.

Hi @mara004 👋,

Thanks for the update 👍 
We have removed the conda support / install option already some time ago (because the download numbers were minimal compared to pypi and did not justify the effort) - I saw your discussion thread and will try to read later today 😄

**Comment by mara004** [comment]
> because the download numbers were minimal compared to pypi

Yes, same thing at our end. The only one that seems to have a notable download count happens to be the conda-forge port. Again it's not good, but to me this indicates that that's what conda users are really looking for – not custom channels. (see also https://github.com/mindee/doctr/issues/1452#issuecomment-4191459886)

**Comment by mara004** [comment]
I think I'll follow suit and remove pypdfium2's conda packaging.
I drafted a changelog entry that will give a brief summary as to why:

> Removed pypdfium2's conda packaging following [thorough](https://github.com/mindee/doctr/discussions/2127) [consideration](https://github.com/mindee/doctr/issues/113#issuecomment-5340008535).
> Key reasons include that it was over-complex and not agnostic of our own build strategies, as a result of outsourcing the pdfium dependency (which was the only viable option prior to [CEP 20](https://github.com/conda/ceps/blob/main/cep-0020.md) – our conda packaging layout predates that change).
> Along with tight storage limits at `anaconda.org`, pypdfium2's conda packages ended up covering far less platforms than we do with PyPI wheels.
> To add to that, builds in a custom channel are not accessible to dependents within the main anaconda/conda-forge ecosystems themselves, which resulted in negligible demand compared to PyPI.
> Conda is effectively a *third-party* package environment similar to nixpkgs or Linux/BSD distribution packaging, unlike PyPI, which is a first-party package index where upstream authors publish directly.

**Comment by felixdittrich92** [comment]
> I think I'll follow suit and remove pypdfium2's conda packaging. I drafted a changelog entry that will give a brief summary as to why:
> 
> > Removed pypdfium2's conda packaging following [thorough](https://github.com/mindee/doctr/discussions/2127) [consideration](https://github.com/mindee/doctr/issues/113#issuecomment-5340008535).
> > Key reasons include that it was over-complex and not agnostic of our own build strategies, as a result of outsourcing the pdfium dependency (which was the only viable option prior to [CEP 20](https://github.com/conda/ceps/blob/main/cep-0020.md) – our implementation predated this change).
> > Along with tight storage limits at `anaconda.org`, pypdfium2's conda packages ended up covering far less platforms than we do with PyPI wheels.
> > To add to that, builds in a custom channel are not accessible to dependents within the main anaconda/conda-forge ecosystems themselves, which resulted in negligible demand compared to PyPI.

Sounds good 👍 
I still have the conda builds in https://github.com/felixdittrich92/OnnxTR but I will drop it also within the next release (same here - 0 downloads the last 6 months vs 110,287 times last month on pypi)

**Comment by mara004** [comment]
While I do believe there is much less demand for conda packages than PyPI, I have a feeling their download stats might not be entirely reliable?

`pypdfium2_raw` shows 422 downloads per the last 6 months, `pdfium-binaries` 0.
`pypdfium2_raw` depends on `pdfium-binaries`, so everyone who installs `pypdfium2_raw` would also get `pdfium-binaries`.
Meaning these figures are contradictory. Unless they don't count indirect downloads? But if that were the case, the numbers would be rendered meaningless IMHO.

Also `pypdfium2_helpers` reads 5 downloads per the last 6 months. Do people really install `pypdfium2_raw` without `pypdfium2_helpers`? I cannot make sense of these numbers.
